x-sl-defaults: &sl-defaults
  image: clem16/simplelogin-app:$SL_VERSION
  env_file: .env
  volumes:
    - ./pgp:/sl/pgp
    - ./upload:/code/static/upload
    - ./dkim.key:/dkim.key
    - ./scripts:/scripts:ro

services:

  ## SIMPLE LOGIN
  ## ============
  
  postgres:
    image: postgres:12.1
    container_name: sl-db
    env_file: .env
    healthcheck:
      test: [ "CMD-SHELL", "PGPASSWORD=$$POSTGRES_PASSWORD pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h 127.0.0.1 -p 5432 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - ./db:/var/lib/postgresql/data
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: ${SL_DB_MEMORY_LIMIT:-512M}
        reservations:
          memory: ${SL_DB_MEMORY_RESERVATION:-256M}

  migration:
    <<: *sl-defaults
    command: [ "bash", "/scripts/run-migration.sh" ]
    container_name: sl-migration
    depends_on:
      postgres:
        condition: service_healthy

  init:
    <<: *sl-defaults
    command: [ "python", "init_app.py" ]
    container_name: sl-init
    depends_on:
      migration:
        condition: service_completed_successfully

  app:
    <<: *sl-defaults
    container_name: sl-app
    entrypoint: ["/scripts/resource-optimized-entrypoint.sh", "app"]
    networks:
      - traefik
      - default
    restart: unless-stopped
    depends_on:
      init:
        condition: service_completed_successfully
    deploy:
      resources:
        limits:
          memory: ${SL_APP_MEMORY_LIMIT:-1G}
        reservations:
          memory: ${SL_APP_MEMORY_RESERVATION:-256M}
    labels:
      - traefik.enable=true
      - traefik.http.services.sl-app.loadbalancer.server.port=7777
      - traefik.http.routers.sl-app.service=sl-app
      - traefik.http.routers.sl-app.middlewares=sts
      - traefik.http.routers.sl-app.rule=Host("${SUBDOMAIN:-app}.${DOMAIN:?DOMAIN_not_set}")
      - traefik.http.routers.sl-app.tls.certresolver=${LE_CHALLENGE:-tls}
      ## redirect http(s)://$DOMAIN -> https://$SUBDOMAIN.$DOMAIN
      - traefik.http.routers.${LE_CHALLENGE:-tls}.rule=Host("${DOMAIN}")
      - traefik.http.routers.${LE_CHALLENGE:-tls}.tls.certresolver=${LE_CHALLENGE:-tls}
      - traefik.http.routers.dns.tls.domains[0].main=${DOMAIN}
      - traefik.http.routers.dns.tls.domains[0].sans=*.${DOMAIN}
      - traefik.http.routers.${LE_CHALLENGE:-tls}.middlewares=sts,redir
      - traefik.http.middlewares.redir.redirectregex.regex=^https?://${DOMAIN}/?.*
      - traefik.http.middlewares.redir.redirectregex.replacement=https://${SUBDOMAIN:-app}.${DOMAIN}
      ## add STS Header for $DOMAIN and all subdomains
      - traefik.http.middlewares.sts.headers.stsSeconds=31536000
      - traefik.http.middlewares.sts.headers.sslRedirect=true
      - traefik.http.middlewares.sts.headers.forceSTSHeader=true
      - traefik.http.middlewares.sts.headers.stsIncludeSubdomains=true
      ## only set stsPreload=true, after registering your domain on hstspreload.org
      - traefik.http.middlewares.sts.headers.stsPreload=false
      ## static response for `mta-sts` subdomain 
      ## These labels are only active when MTA_STS_INTERNAL_ENABLED is not explicitly set to 'false'
      ## Set MTA_STS_MODE=external or MTA_STS_MODE=disabled in .env to disable internal hosting
      - traefik.http.routers.mta-sts.rule=Host("mta-sts.${DOMAIN}") && PathPrefix("/.well-known/mta-sts.txt")
      - traefik.http.routers.mta-sts.service=noop@internal
      - traefik.http.routers.mta-sts.middlewares=mta-sts-response
      - traefik.http.middlewares.mta-sts-response.plugin.staticresponse.StatusCode=200
      - "traefik.http.middlewares.mta-sts-response.plugin.staticresponse.Body=version: STSv1\nmode: ${MTA_STS_POLICY_MODE:-testing}\nmx: ${SUBDOMAIN:-app}.${DOMAIN}\nmax_age: ${MTA_STS_MAX_AGE:-86400}"
      ## Note: The following parameters have to be set in traefik static config, to activate `staticresponse` plugin:
      # experimental.plugins.staticresponse.moduleName=github.com/jdel/staticresponse
      # experimental.plugins.staticresponse.version=v0.0.1

  email:
    <<: *sl-defaults
    entrypoint: ["/scripts/resource-optimized-entrypoint.sh", "email", "python", "email_handler.py"]
    container_name: sl-email
    restart: unless-stopped
    depends_on:
      init:
        condition: service_completed_successfully
    deploy:
      resources:
        limits:
          memory: ${SL_EMAIL_MEMORY_LIMIT:-512M}
        reservations:
          memory: ${SL_EMAIL_MEMORY_RESERVATION:-128M}

  job-runner:
    <<: *sl-defaults
    entrypoint: ["/scripts/resource-optimized-entrypoint.sh", "job-runner", "python", "job_runner.py"]
    container_name: sl-job-runner
    restart: unless-stopped
    depends_on:
      init:
        condition: service_completed_successfully
    deploy:
      resources:
        limits:
          memory: ${SL_JOB_MEMORY_LIMIT:-512M}
        reservations:
          memory: ${SL_JOB_MEMORY_RESERVATION:-128M}
